using PointOfSale.App.Models;

namespace PointOfSale.App.Services;

public static class ReportCatalog
{
    public static readonly IReadOnlyList<ReportDefinition> Definitions = new List<ReportDefinition>
    {
        new("Sales Tracking", "Daily Sales Summary",
            "Track daily revenue, transactions, and average sale performance.",
            "Gross/net sales, transactions, units sold, discounts, taxes, refunds.",
            "Daily and weekly"),
        new("Sales Tracking", "Weekly/Monthly Sales Trends",
            "Compare sales periods to identify growth and seasonality.",
            "Period sales, growth, average daily sales, peak times, gross profit, margin.",
            "Weekly and monthly"),
        new("Sales Tracking", "Sales by Product",
            "Identify top and slow-moving items for reordering or markdowns.",
            "Units sold, revenue per item, total sales %, return rate, last sale date.",
            "Weekly or monthly"),
        new("Sales Tracking", "Sales by Category",
            "Spot revenue drivers across product groups.",
            "Revenue per category, units, category margin, growth.",
            "Monthly or seasonal"),
        new("Sales Tracking", "Sales by Time/Daypart",
            "Optimize staffing and promotions for peak hours.",
            "Sales and transactions per hour/day, average sale per hour.",
            "Weekly"),
        new("Sales Tracking", "Sales by Customer",
            "Identify VIP customers and purchasing patterns.",
            "Spend per customer, visits, average order value.",
            "Monthly or quarterly"),
        new("Sales Tracking", "Discounts & Promotions",
            "Measure impact of discounts on profitability.",
            "Total discounts, orders using discounts, uplift in units.",
            "Weekly or post-promo"),
        new("Inventory Management", "Inventory On Hand",
            "Track stock levels and inventory value.",
            "On-hand qty by SKU, total inventory value, location breakdown.",
            "Weekly or daily"),
        new("Inventory Management", "Low Stock / Reorder",
            "Alert for items below threshold to prevent stockouts.",
            "Current qty, reorder point, days of supply.",
            "Daily or weekly"),
        new("Inventory Management", "Product Performance",
            "Monitor sell-through and dead stock.",
            "Units sold per period, sell-through rate, last sale date.",
            "Weekly or monthly"),
        new("Inventory Management", "Inventory Turnover",
            "Gauge inventory efficiency and cash flow.",
            "Turnover ratio, sell-through per SKU/category.",
            "Monthly or quarterly"),
        new("Inventory Management", "COGS Report",
            "Assess gross profit and purchasing costs.",
            "COGS, gross margin $, gross margin %.",
            "Monthly"),
        new("Inventory Management", "Purchase Order Status",
            "Track outstanding and fulfilled purchase orders.",
            "POs by vendor, expected vs received dates, status.",
            "Weekly or as needed"),
        new("Inventory Management", "Goods Received (GRN)",
            "Verify deliveries match purchase orders.",
            "Received vs ordered qty, discrepancies, vendor details.",
            "Per delivery or weekly"),
        new("Inventory Management", "Inventory Adjustments / Shrinkage",
            "Audit variances and losses.",
            "Adjustments by SKU, reason codes, dollar impact.",
            "Monthly"),
        new("Inventory Management", "Expiry / Wastage",
            "Minimize loss from perishable goods.",
            "Units near expiry, expired cost, batch details.",
            "Daily or weekly"),
        new("Customer Insights", "Top Customers",
            "Recognize and reward VIP customers.",
            "Total spend, visit frequency, average basket size.",
            "Monthly or quarterly"),
        new("Customer Insights", "Customer Purchase History",
            "Provide personalized service and segmentation.",
            "Purchase dates, items, total spend.",
            "On-demand or monthly"),
        new("Customer Insights", "Customer Segment / Loyalty",
            "Evaluate loyalty program performance.",
            "New vs returning, points earned/redeemed, redemption rates.",
            "Monthly"),
        new("Customer Insights", "Customer Retention/Churn",
            "Measure repeat purchase behavior.",
            "Repeat purchase %, time between visits, lifetime value.",
            "Quarterly"),
        new("Employee Performance", "Sales by Employee",
            "Spot top performers and coaching needs.",
            "Sales per employee, transactions, average sale, items per transaction.",
            "Weekly or monthly"),
        new("Employee Performance", "Transactions by Employee",
            "Audit sales, returns, and payments by staff.",
            "Sales vs returns/voids, cash/card totals.",
            "Weekly or as needed"),
        new("Employee Performance", "Shift / Sales per Hour",
            "Assess labor productivity.",
            "Sales per shift/hour, labor cost vs sales.",
            "Monthly or per pay period"),
        new("Employee Performance", "Training & Compliance",
            "Track certification completion.",
            "Training modules completed, certification dates.",
            "Quarterly"),
        new("Financial Reports", "Financial Summary",
            "Summarize daily revenue and deductions.",
            "Gross sales, discounts, taxes, refunds, net sales.",
            "Daily and monthly"),
        new("Financial Reports", "End-of-Day / Cash Drawer",
            "Provide register closeout accountability.",
            "Opening float, cash/card totals, over/short.",
            "Daily"),
        new("Financial Reports", "Tax Summary",
            "Ensure tax compliance and filing accuracy.",
            "Taxable sales by rate, total tax collected.",
            "Monthly or quarterly"),
        new("Financial Reports", "Payment/Tender Type",
            "Reconcile payments and understand preferences.",
            "Sales amount and count by payment type.",
            "Daily or weekly"),
        new("Financial Reports", "Profit & Loss / Gross Margin",
            "Track profitability including COGS and expenses.",
            "Sales, COGS, gross profit $, margin %, net profit.",
            "Monthly or quarterly"),
        new("Financial Reports", "Refunds and Returns",
            "Detect patterns in returns and lost sales.",
            "Return count/value by item/customer, refund reasons.",
            "Weekly or monthly"),
        new("Financial Reports", "Discounts & Promotional Costs",
            "Quantify promotion costs and ROI.",
            "Discount totals, promo codes, lift.",
            "Monthly or post-campaign"),
        new("Financial Reports", "Gift Card Activity",
            "Track gift card liability and usage.",
            "Gift card sales, redemptions, outstanding balance.",
            "Monthly")
    };
}
